import os

DATABASE_USER = os.environ.get('DATABASE_USER')
DATABASE_PASSWORD = os.environ.get('DATABASE_PASSWORD')
DATABASE_HOST = os.environ.get('DATABASE_HOST')
DATABASE_PORT = os.environ.get('DATABASE_PORT')
DATABASE_NAME = os.environ.get('DATABASE_NAME')

DB_URL_CONNECTION = f'postgresql://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}'
#
# QUART_CORS_ALLOW_ORIGIN
# QUART_CORS_ALLOW_CREDENTIALS
# QUART_CORS_ALLOW_METHODS
# QUART_CORS_ALLOW_HEADERS
# QUART_CORS_EXPOSE_HEADERS
# QUART_CORS_MAX_AGE

config = {
    'DATABASE_URL': DB_URL_CONNECTION,
    'JWT_SECRET_KEY': 'secret',
    'MAX_CONTENT_UPLOADED_LENGTH': 5 * 1024 * 1024,
}